#!/bin/bash
# install.sh — set up SAI Ver.2 on macOS with pen pressure.
#
# Automates the mechanical parts: creates a Wine prefix, copies SAI into it,
# installs the custom wintab32.dll + override, and generates a one-click
# launcher configured for your paths. You still do the manual steps the
# installer can't (install Wine, download SAI, grant permissions, add license,
# enable "Use WinTab API") — it prints those at the end.
#
# Override any path via env, e.g.:
#   SAI_PREFIX=~/mysai  SAI2_SRC=~/Downloads/sai2-...  ./install.sh
set -e

REPO="$(cd "$(dirname "$0")" && pwd)"
PREFIX="${SAI_PREFIX:-$HOME/SAI2-pressure}"
WINE="${WINE:-/Applications/Wine Staging.app/Contents/Resources/wine/bin/wine}"
DLL="$REPO/wintab-src/wintab32.dll"
HELPER="$REPO/wacom-helper/wacom-pressure-helper"
PRESSURE_FILE="$PREFIX/drive_c/wt_pressure.txt"

echo "== SAI pen-pressure installer =="
echo "  prefix : $PREFIX"
echo "  wine   : $WINE"

# --- prerequisites ----------------------------------------------------------
if [ ! -x "$WINE" ]; then
  echo "ERROR: Wine not found at:"
  echo "  $WINE"
  echo "Install Gcenx 'Wine Staging' (https://github.com/Gcenx/macOS_Wine_builds/releases)"
  echo "and put 'Wine Staging.app' in /Applications, or set WINE=/path/to/wine."
  exit 1
fi
if [ ! -f "$DLL" ]; then
  echo "ERROR: prebuilt wintab32.dll not found at $DLL"
  echo "Build it first (see README 'Build from source')."
  exit 1
fi
if [ ! -x "$HELPER" ]; then
  echo "Note: helper binary not found; attempting to build it..."
  ( cd "$REPO/wacom-helper" && swiftc -O -o wacom-pressure-helper main.swift PressureCore.swift ) \
    || { echo "ERROR: could not build the helper (needs Xcode command-line tools)."; exit 1; }
fi

# --- locate SAI2 ------------------------------------------------------------
if [ -z "${SAI2_SRC:-}" ]; then
  echo ""
  echo "Enter the path to your extracted SAI2 folder (the one containing sai2.exe):"
  read -r SAI2_SRC
fi
SAI2_SRC="${SAI2_SRC/#\~/$HOME}"
if [ ! -f "$SAI2_SRC/sai2.exe" ]; then
  echo "ERROR: sai2.exe not found in: $SAI2_SRC"
  exit 1
fi

# --- create the prefix ------------------------------------------------------
export WINEPREFIX="$PREFIX"
export WINEDEBUG=-all
if [ ! -d "$PREFIX/drive_c" ]; then
  echo "Creating Wine prefix (first run downloads/initialises; may take a minute)..."
  "$WINE" wineboot -i >/dev/null 2>&1 || true
  "$WINE" wineboot -u >/dev/null 2>&1 || true
fi

# --- install SAI ------------------------------------------------------------
echo "Installing SAI into the prefix..."
mkdir -p "$PREFIX/drive_c/SAI2"
cp -R "$SAI2_SRC/." "$PREFIX/drive_c/SAI2/"

# --- install the pressure bridge -------------------------------------------
echo "Installing wintab32.dll + override..."
mkdir -p "$PREFIX/drive_c/windows/system32"
cp "$DLL" "$PREFIX/drive_c/windows/system32/wintab32.dll"
"$WINE" reg add "HKCU\\Software\\Wine\\DllOverrides" /v wintab32 /t REG_SZ /d "native,builtin" /f >/dev/null 2>&1
echo 0 > "$PRESSURE_FILE"

# --- generate a personal one-click launcher ---------------------------------
LAUNCHER="$REPO/Start SAI2 (my setup).command"
cat > "$LAUNCHER" <<EOF
#!/bin/bash
# Auto-generated by install.sh for this machine.
export WINEPREFIX="$PREFIX"
export WINEDEBUG=-all
export WT_PRESSURE_FILE="$PRESSURE_FILE"
HELPER="$HELPER"
WINE="$WINE"

echo 0 > "\$WT_PRESSURE_FILE"
"\$HELPER" > "$PREFIX/helper.log" 2>&1 &
HP=\$!
trap 'echo 0 > "\$WT_PRESSURE_FILE" 2>/dev/null; kill \$HP 2>/dev/null' EXIT INT TERM
rm -f "$PREFIX/drive_c/wtlog.txt"
echo "Pen pressure active. Close SAI to stop."
cd "$PREFIX/drive_c/SAI2"
"\$WINE" sai2.exe
EOF
chmod +x "$LAUNCHER"

# --- done -------------------------------------------------------------------
cat <<EOF

== Installed. Remaining MANUAL steps ==

1. Permissions: System Settings -> Privacy & Security -> grant your terminal
   BOTH 'Accessibility' and 'Input Monitoring', then restart the terminal.

2. License (to save): put your sai-*.slc into:
     $PREFIX/drive_c/SAI2/
   then restart SAI.

3. In SAI: Others -> Options -> Pen Tablet -> 'Use WinTab API', restart SAI.

Launch it any time by double-clicking:
   $LAUNCHER

Kill switch if needed:  echo 0 > "$PRESSURE_FILE"
EOF
